### ISSUE TITLE
Bug visual de la UI de armas

### ISSUE THREAD

**Issue by Zorromatamoscas** [Proyectos1-FDI-UCM/c2022-Grupo08#12]
Descripción:
Al morir con un arma recogida y reiniciar el juego, te sale en la UI como si ya tuvieras el arma sin haberla recogido pero cuando intentas usarla, no funciona hasta que la recoges de nuevo.
Pasos:
1.Iniciar el juego
2. Recoger un arma
3.Dejar que te maten
4. Reiniciar el juego
5.Observar la UI de armas

Captura:
![Captura_de_pantalla_139](https://user-images.githubusercontent.com/99506562/165828033-b90d692a-711e-4735-b6de-e6587193bfe4.png)

**Comment by PabloCerrada** [comment]
Arreglado
