### ISSUE TITLE
Recolección de objetos rara

### ISSUE THREAD

**Issue by PabloGonzalezArroyoo** [Proyectos1-FDI-UCM/c2022-Grupo08#13]
### Descripción

En algunas ocasiones, al recoger objetos que están unos al lado de otros hace que cogas el que no querías.

### Pasos

1. Posicionarse al lado de un objeto que tenga también otro cerca (balas en el pasillo, armas en el inicio)
2. Pulsar E para recoger un objeto.
3. Ver si se coge el que esperabas o no.

### Captura de pantalla o vídeo

[![Vídeo](https://img.youtube.com/vi/WfmVkE0mS1U/0.jpg)](https://youtu.be/WfmVkE0mS1U)

**Comment by alvarolozrod** [comment]
Todo arreglado
