### ISSUE TITLE
Sonido Daño Jugador - Retraso

### ISSUE THREAD

**Issue by Rafaa0514** [Proyectos1-FDI-UCM/c2022-Grupo08#14]
### Descripción
El sonido correspondiente a cuando el jugador recibe daño se reproduce con retraso, lo cuál hace que al recibir daño de dos enemigos en un intervalo corto de tiempo se superpongan (incluso si te matan se siguen escuchando en la pantalla de GameOver)

### Pasos
1. Deja que un enemigo te haga daño
2. Espera a escuchar el sonido
3. Deja que 2 enemigos te hagan en un corto período de tiempo
4. Escucha la superposición de los sonidos

### Video
[![Texto alternativo](https://img.youtube.com/vi/-8p25I8Q2y8/0.jpg)](https://youtu.be/-8p25I8Q2y8)

**Comment by AgusCDT** [comment]
Arreglado
