### ISSUE TITLE
Personaje se ve a través de las puertas no accedidas anteriormente

### ISSUE THREAD

**Issue by PabloGonzalezArroyoo** [Proyectos1-FDI-UCM/c2022-Grupo08#2]
### Descripción

Si te acercas lentamente a las puertas, puedes llegar a ver al personaje aunque no sea visible la siguiente zona.

### Pasos 

1. Posicionar al personaje enfrente de la puerta a entrar.
2. Entrar muy despacio, dando toquecitos a S.

### Captura de pantalla o vídeo

[![Texto alternativo](https://img.youtube.com/vi/rpWyFk0p5w0/0.jpg)](https://youtu.be/rpWyFk0p5w0)

**Comment by PabloCerrada** [comment]
arreglado
