### ISSUE TITLE
Fallos tridimensionalidad

### ISSUE THREAD

**Issue by LittleWallSt** [Proyectos1-FDI-UCM/c2022-Grupo08#3]
### Descripción

Algunos objetos rompen por completo la sensación de tridimensionalidad

### Pasos 

1. Acercarse a ciertos objetos
2. Atravesarlos o quedarse atascado en ciertos sitios sin sentido
3. (En el siguiente pdf se indican todos los encontrados)

### Captura de pantalla o vídeo
[Capturas fallos con objetos.pdf](https://github.com/Proyectos1-FDI-UCM/c2022-Grupo08/files/8581999/Capturas.fallos.con.objetos.pdf)

**Comment by AgusCDT** [comment]
Arreglados
