### ISSUE TITLE
Puerta que no se abre

### ISSUE THREAD

**Issue by Zorromatamoscas** [Proyectos1-FDI-UCM/c2022-Grupo08#6]
Descripción:
La puerta que hay nada más salir al pasillo, a la derecha no se abre y es impasable.
Pasos:
1. Salir al primer pasillo desde el spawn.
2. Ir a la puerta justa a la derecha
3. Intentar cruzar
Captura:
![Captura](https://user-images.githubusercontent.com/99506562/165820078-253e3766-b603-4592-806f-3c7ad7ea4bb0.PNG)

**Comment by AgusCDT** [comment]
Esta la cerramos porque intencionalmente no se puede acceder, ya que se abre una vez activas la electricidad
