### ISSUE TITLE
Colliders colocados de forma errónea

### ISSUE THREAD

**Issue by Zorromatamoscas** [Proyectos1-FDI-UCM/c2022-Grupo08#7]
Descipción:
Los colliders de algunos objetos no se corresponden con su representación visual.
Pasos:
1. Iniciar el juego
2. Chocar con todos los objetos a la vista

Capturas y videos:
https://youtu.be/HGiROqCFhzA
https://youtu.be/Get0zOP2WME
https://youtu.be/kk1qfw9dIyM
![Captura](https://user-images.githubusercontent.com/99506562/165821058-ace680d9-7ede-4d9e-ae2e-2d31f3a7f957.PNG)

**Comment by AgusCDT** [comment]
Arreglados
