### ISSUE TITLE
El rango de ataque de los zombies es desigual

### ISSUE THREAD

**Issue by Zorromatamoscas** [Proyectos1-FDI-UCM/c2022-Grupo08#9]
Descripción:
Cuando te posicionas encima o debajo de un zombie, su rango de ataque es mucho más grande que horizontalmente y es poco realista, dando situaciones en las que te quedas encerrado en una esquina.
Pasos:
1. Iniciar el juego
2. Salir del spawn inicial
3. Encontrar un zombie enemigo
4. Situarte verticalmente a él
5. Dejar que te pegue

Capturas  y video:
https://youtu.be/tao7Reijx8c

**Comment by AgusCDT** [comment]
Arreglado
